Repository beyond-all-reason/Beyond-All-Reason, pull requests merged in 2024-10, with the labels that each got.

#3806 Show wait state as toggle
  luaui/Widgets/gui_ordermenu.lua
Labels: UI

#3688 Feature: Factory Quotas
  language/en/interface.json
  luarules/configs/customcmds.h.lua
  luarules/gadgets/cmd_factory_stop_production.lua
  luarules/gadgets/unit_factory_quota.lua
  luaui/Widgets/gui_buildmenu.lua
  luaui/Widgets/gui_gridmenu.lua
  luaui/Widgets/unit_factory_quota.lua
  luaui/configs/hotkeys/grid_keys.txt
  luaui/configs/hotkeys/legacy_keys.txt
Labels: Approved, UI

#3871 corsolar yardmap update
  units/CorBuildings/LandEconomy/corsolar.lua
Labels: Awaiting GDT Approval
