Repository beyond-all-reason/Beyond-All-Reason, pull requests merged in 2024-12, with the labels that each got.

#3603 Polygon map start boxes
  luaui/Widgets/Shaders/map_startpolygon_gl4.frag.glsl
  luaui/Widgets/Shaders/map_startpolygon_gl4.vert.glsl
  luaui/Widgets/map_startbox.lua
  luaui/Widgets/map_startpolygon_gl4.lua
  luaui/images/rapt-tileable_v001_small.tga
  luaui/images/rapt-tileable_v001_small_alpha.tga
  luaui/images/rapt-tileable_v002_small.tga
  luaui/images/scav-tileable_v001-alpha.tga
  luaui/images/scav-tileable_v001_small.tga
  luaui/images/scav-tileable_v002_small.tga
  tools/StartScripts/startscript_startboxes.txt
Labels: Enhancement

#3922 Torpedo bomber Range reduction
  units/ArmAircraft/T2/armlance.lua
  units/CorAircraft/T2/cortitan.lua
Labels: Awaiting BLT Approval

#3732 Tweaks and improvement to declutter defense-ranges
  luaui/Widgets/Shaders/attack_range_gl4.vert.glsl
  luaui/Widgets/Shaders/weapon_range_rings_unified_gl4.frag.glsl
  luaui/Widgets/Shaders/weapon_range_rings_unified_gl4.vert.glsl
  luaui/Widgets/gui_anti_ranges.lua
  luaui/Widgets/gui_attackrange_gl4.lua
  luaui/Widgets/gui_defenserange.lua
  luaui/Widgets/gui_defenserange_gl4.lua
  units/ArmBots/T2/armaak.lua
  units/ArmBuildings/LandUtil/armmine1.lua
  units/ArmBuildings/LandUtil/armmine2.lua
  units/ArmBuildings/LandUtil/armmine3.lua
  units/ArmBuildings/SeaUtil/armfmine3.lua
  units/ArmGantry/armthor.lua
  units/ArmShips/T2/armbats.lua
  units/ArmShips/T2/armepoch.lua
  units/ArmShips/T2/armlship.lua
  units/ArmShips/T2/armmship.lua
  units/ArmShips/armpship.lua
  units/CorAircraft/T2/corcrwh.lua
  units/CorBots/T2/coraak.lua
  units/CorBuildings/LandUtil/cormine1.lua
  units/CorBuildings/LandUtil/cormine2.lua
  units/CorBuildings/LandUtil/cormine3.lua
  units/CorBuildings/SeaUtil/corfmine3.lua
  units/CorGantry/corjugg.lua
  units/CorGantry/corkorg.lua
  units/CorShips/T2/corbats.lua
  units/CorShips/T2/corblackhy.lua
  units/CorShips/T2/cormship.lua
  units/Legion/Air/T2 Air/legfort.lua
  units/Legion/Air/T2 Air/legheavydrone.lua
  units/Legion/Air/T2 Air/legionnaire.lua
  units/Legion/Air/T2 Air/legvenator.lua
  units/Legion/Air/legdrone.lua
  units/Legion/Defenses/legbombard.lua
  units/Legion/Ships/leghastatus.lua
  units/Legion/Ships/leghastatusalt.lua
  units/Legion/Ships/legportent.lua
  units/Legion/T3/legpede.lua
Labels: UI

#4078 cmd_context_build: Avoid lua error because of missing hardcoded unitdefs.
  luaui/Widgets/cmd_context_build.lua
Labels: Bug

#4073 Legion javelin
  gamedata/armordefs.lua
  gamedata/icontypes.lua
  icons/legjav.png
  language/en/units.json
  luarules/configs/gui_soundeffects.lua
  luarules/gadgets/unit_continuous_aim.lua
  luaui/configs/DeferredLightsGL4config.lua
  luaui/configs/buildmenu_sorting.lua
  luaui/configs/gridmenu_layouts.lua
  objects3d/Units/legjav.s3o
  objects3d/Units/legjav_dead.s3o
  scripts/Units/legjav.bos
  scripts/Units/legjav.cob
  unitpics/legjav.dds
  units/Legion/Labs/leggant.lua
  units/Legion/T3/legjav.lua
Labels: Legion

#4074 Add legion factories made by protar/ghoulish
  luaui/configs/DeferredLightsGL4config.lua
  objects3d/Units/legaap.s3o
  objects3d/Units/legaap_dead.s3o
  objects3d/Units/legalab.s3o
  objects3d/Units/legalab_dead.s3o
  objects3d/Units/legap.s3o
  objects3d/Units/legap_dead.s3o
  scripts/Units/legaap.bos
  scripts/Units/legaap.cob
  scripts/Units/legalab.bos
  scripts/Units/legalab.cob
  scripts/Units/legap.bos
  scripts/Units/legap.cob
  unitpics/legaap.dds
  unitpics/legalab.dds
  unitpics/legap.dds
  units/Legion/Labs/legaap.lua
  units/Legion/Labs/legalab.lua
  units/Legion/Labs/legap.lua
Labels: Legion
