Repository beyond-all-reason/Beyond-All-Reason, pull requests merged in 2025-08, with the labels that each got.

#4955 fix(unit_evolution): part 4 chunking
  luarules/gadgets/unit_evolution.lua
Labels: Awaiting GDT Approval

#5619 New widget to set persistently targeted unit type
  luaui/Widgets/unit_alt_set_target_type.lua
Labels: Awaiting GDT Approval

#5582 Charybdis model update
  luarules/configs/collisionvolumes.lua
  objects3d/Units/legehovertank.s3o
  objects3d/Units/legehovertank_dead.s3o
  scripts/Units/legehovertank.bos
  scripts/Units/legehovertank.cob
  scripts/Units/legmh.bos
  scripts/Units/legmh.cob
  unitpics/legehovertank.dds
  units/Legion/T3/legehovertank.lua
Labels: Legion

#5714 Updates Thug Model
  luaui/configs/DeferredLightsGL4config.lua
  objects3d/Units/corthud.s3o
  objects3d/Units/corthud_dead.s3o
  scripts/Units/corthud.bos
  scripts/Units/corthud.cob
  unitpics/corthud.dds
  units/CorBots/corthud.lua
Labels: Modelling
