Repository beyond-all-reason/Beyond-All-Reason, pull requests merged in 2025-06, with the labels that each got.

#5135 Update to Legion T2 Bot Lab grid menu layout
  luaui/configs/gridmenu_layouts.lua
Labels: Legion

#4879 feat(blueprints): automatic side substitution
  gamedata/sidedata.lua
  gamedata/sides_enum.lua
  luaui/Include/blueprint_substitution/definitions.lua
  luaui/Include/blueprint_substitution/logic.lua
  luaui/Include/blueprint_substitution/reports.lua
  luaui/Widgets/api_blueprint.lua
  luaui/Widgets/cmd_blueprint.lua
  luaui/Widgets/gui_pregame_build.lua
Labels: Blueprint Widget

#5275 Barb legion: 'commander' and 'economy' levels.
  luarules/configs/BARb/stable/config/easy/commander_leg.json
  luarules/configs/BARb/stable/config/easy/economy_leg.json
  luarules/configs/BARb/stable/config/hard/commander_leg.json
  luarules/configs/BARb/stable/config/hard/economy_leg.json
  luarules/configs/BARb/stable/config/hard_aggressive/commander_leg.json
  luarules/configs/BARb/stable/config/hard_aggressive/economy_leg.json
  luarules/configs/BARb/stable/config/medium/commander_leg.json
  luarules/configs/BARb/stable/config/medium/economy_leg.json
Labels: AI

#5279 Barb legion: 'buildchain' difficulty levels
  luarules/configs/BARb/stable/config/easy/build_chain_leg.json
  luarules/configs/BARb/stable/config/hard/build_chain_leg.json
  luarules/configs/BARb/stable/config/hard_aggressive/build_chain_leg.json
  luarules/configs/BARb/stable/config/medium/build_chain_leg.json
Labels: AI

#5282 Barb legion 'factory' levels
  luarules/configs/BARb/stable/config/easy/factory_leg.json
  luarules/configs/BARb/stable/config/hard/factory_leg.json
  luarules/configs/BARb/stable/config/hard_aggressive/factory_leg.json
  luarules/configs/BARb/stable/config/medium/factory_leg.json
Labels: AI

#5292 Barb legion assorted fixes
  luarules/configs/BARb/stable/config/easy/behaviour_leg.json
  luarules/configs/BARb/stable/config/easy/factory_leg.json
  luarules/configs/BARb/stable/config/hard/behaviour_leg.json
  luarules/configs/BARb/stable/config/hard/factory_leg.json
  luarules/configs/BARb/stable/config/hard_aggressive/behaviour_leg.json
  luarules/configs/BARb/stable/config/hard_aggressive/factory_leg.json
  luarules/configs/BARb/stable/config/medium/behaviour_leg.json
  luarules/configs/BARb/stable/config/medium/factory_leg.json
Labels: AI

#5048 Bug fix for lava slow
  luarules/gadgets/map_lava.lua
Labels: Awaiting GDT Approval

#5218 Arm Twilight Colvol update
  units/ArmBuildings/LandEconomy/armamex.lua
Labels: Modelling

#5206 Sol Invictus heatray aiming fix
  objects3d/Units/legeheatraymech.s3o
  scripts/Units/legeheatraymech.bos
  scripts/Units/legeheatraymech.cob
Labels: Legion, Script / Animation
