Repository beyond-all-reason/Beyond-All-Reason, pull requests merged in 2025-04, with the labels that each got.

#4637 Legion Phalanx Remodel
  gamedata/icontypes.lua
  language/en/units.json
  objects3d/Units/legshot.s3o
  objects3d/Units/legshot_dead.s3o
  scripts/Units/legkark.bos
  scripts/Units/legkark.cob
  scripts/Units/legshot.bos
  scripts/Units/legshot.cob
  unitpics/legshot.dds
  units/Legion/Bots/T2 Bots/legshot.lua
Labels: Legion

#4613 Legion T3 Unit: Pilum
  gamedata/alldefs_post.lua
  gamedata/armordefs.lua
  gamedata/icontypes.lua
  gamedata/scavengers/unitdef_post.lua
  icons/inverted/legbunk.png
  icons/legbunk.png
  language/en/units.json
  luarules/configs/gui_soundeffects.lua
  luarules/configs/scav_spawn_defs.lua
  luarules/gadgets/unit_continuous_aim.lua
  luaui/configs/DeferredLightsGL4config.lua
  luaui/configs/buildmenu_sorting.lua
  luaui/configs/gridmenu_layouts.lua
  objects3d/Units/legbunk.s3o
  objects3d/Units/legbunk_dead.s3o
  scripts/Units/legbunk.bos
  scripts/Units/legbunk.cob
  scripts/constant_acceleration_turret_turning_1.h
  scripts/constant_acceleration_turret_turning_2.h
  scripts/constant_acceleration_turret_turning_3.h
  unitpics/legbunk.dds
  units/Legion/T3/legbunk.lua
Labels: Legion

#4485 Special Stun Override Implementation
  luarules/gadgets/unit_paralyze_damage_limit.lua
  weapons/spybombx.lua
Labels: Approved, Scheduled Balance Release

#4673 Fix incorrect UnitCmdDone callin parameter ordering in several places.
  luarules/gadgets.lua
  luarules/gadgets/dbg_unit_callins.lua
  luarules/gadgets/unit_carrier_spawner.lua
  luarules/gadgets/unit_target_on_the_move.lua
  luaui/Widgets/dbg_unit_callins.lua
  luaui/barwidgets.lua
Labels: Bug

#4692 fix hotkey connected to trajectory toggle
  luaui/configs/hotkeys/grid_keys.txt
Labels: Keybinds

#4696 legacy alt+f functionality fix (legacy/grid_keys.txt)
  luaui/configs/hotkeys/grid_keys.txt
  luaui/configs/hotkeys/grid_keys_60pct.txt
  luaui/configs/hotkeys/legacy_keys.txt
  luaui/configs/hotkeys/legacy_keys_60pct.txt
Labels: Keybinds

#4707 Boreas closing animation fix
  scripts/Units/legavroc_clean.bos
  scripts/Units/legavroc_clean.cob
Labels: Legion, Script / Animation

#4642 Belcher and Praetorian animation improvements
  scripts/Units/legbart.bos
  scripts/Units/legbart.cob
  scripts/Units/legbart_clean.bos
  scripts/Units/legbart_clean.cob
  scripts/Units/legeshotgunmech.bos
  scripts/Units/legeshotgunmech.cob
Labels: Legion

#4728 Updated keyboard_layouts.lua to enable workman keyboard layout support
  luaui/configs/keyboard_layouts.lua
Labels: Keybinds

#4829 Legion-amphib-t2
  gamedata/icontypes.lua
  language/en/units.json
  luarules/configs/scav_spawn_defs.lua
  luarules/gadgets/unit_continuous_aim.lua
  luaui/configs/buildmenu_sorting.lua
  luaui/configs/gridmenu_layouts.lua
  objects3d/Units/legamph.s3o
  objects3d/Units/legamph_dead.s3o
  scripts/Units/legamph.bos
  scripts/Units/legamph.cob
  unitpics/legamph.dds
  units/Legion/Bots/T2 Bots/legamph.lua
  units/Legion/Labs/legalab.lua
  units/Legion/Labs/legamsub.lua
Labels: Legion
