Repository beyond-all-reason/Beyond-All-Reason, pull requests merged in 2025-03, with the labels that each got.

#4292 Legion T3 ShieldGen
  gamedata/alldefs_post.lua
  language/en/units.json
  luarules/configs/scav_spawn_defs.lua
  luarules/gadgets/lups_orb.lua
  luaui/Widgets/gfx_lupsgl4_orbs.lua
  luaui/configs/DeferredLightsGL4config.lua
  objects3d/Units/leggatet3.s3o
  objects3d/Units/leggatet3_dead.s3o
  objects3d/Units/leggatet3_dmg.s3o
  scripts/Units/leggatet3.bos
  scripts/Units/leggatet3.cob
  unitpics/leggatet3.dds
  units/Legion/Defenses/leggatet3.lua
Labels: Legion

#4409 Stdev84
  luarules/gadgets/AILoader.lua
  luarules/gadgets/ai/STAI/ai.lua
  luarules/gadgets/ai/STAI/armyhst.lua
  luarules/gadgets/ai/STAI/attackerbst.lua
  luarules/gadgets/ai/STAI/attackhst.lua
  luarules/gadgets/ai/STAI/behaviourfactory.lua
  luarules/gadgets/ai/STAI/buildersbst.lua
  luarules/gadgets/ai/STAI/buildingshst.lua
  luarules/gadgets/ai/STAI/commanderbst.lua
  luarules/gadgets/ai/STAI/damagehst.lua
  luarules/gadgets/ai/STAI/engineerbst.lua
  luarules/gadgets/ai/STAI/labsbst.lua
  luarules/gadgets/ai/STAI/loshst.lua
  luarules/gadgets/ai/STAI/maphst.lua
  luarules/gadgets/ai/STAI/raidbst.lua
  luarules/gadgets/ai/STAI/raidhst.lua
  luarules/gadgets/ai/STAI/targethst.lua
  luarules/gadgets/ai/STAI/taskshst.lua
  luarules/gadgets/ai/STAI/tool.lua
  luarules/gadgets/ai/shard_runtime/shardai.lua
  luarules/gadgets/ai/shard_runtime/spring_lua/map.lua
  luarules/gadgets/ai/shard_runtime/spring_lua/metal.lua
  luarules/gadgets/ai/shard_runtime/spring_lua/unit.lua
  luarules/gadgets/ai/shard_runtime/unit.lua
Labels: Review Session Candidate

#4396 Make grid 's' map to settargetnoground, and 'alt+s' to settarget
  luaui/configs/hotkeys/grid_keys.txt
  luaui/configs/hotkeys/grid_keys_60pct.txt
Labels: Keybinds

#4525 Transports rebalance
  units/ArmAircraft/T2/armdfly.lua
  units/ArmAircraft/armatlas.lua
  units/ArmAircraft/armhvytrans.lua
  units/CorAircraft/T2/corseah.lua
  units/CorAircraft/corhvytrans.lua
  units/CorAircraft/corvalk.lua
Labels: Scheduled Balance Release

#4475 Blitz hitbox
  luarules/configs/collisionvolumes.lua
  units/ArmVehicles/armflash.lua
Labels: Scheduled Balance Release

#4450 Season 2 balance patch
  gamedata/alldefs_post.lua
  luarules/gadgets/unit_hound_weapon_toggle.lua
  scripts/Units/armfido.bos
  scripts/Units/armfido.cob
  scripts/Units/armfido_clean.bos
  scripts/Units/armfido_clean.cob
  scripts/Units/armspy.bos
  scripts/Units/armspy.cob
  scripts/Units/armspy_clean.bos
  scripts/Units/armspy_clean.cob
  scripts/Units/corban.bos
  scripts/Units/corban.cob
  scripts/Units/corban_clean.bos
  scripts/Units/corban_clean.cob
  scripts/Units/corspy.bos
  scripts/Units/corspy.cob
  scripts/Units/corspy_clean.bos
  scripts/Units/corspy_clean.cob
  unitbasedefs/proposed_unit_reworks_defs.lua
  units/ArmAircraft/armthund.lua
  units/ArmBots/T2/armfido.lua
  units/ArmBots/T2/armsptk.lua
  units/ArmBots/T2/armspy.lua
  units/ArmBots/armflea.lua
  units/ArmBots/armpw.lua
  units/ArmBuildings/LandEconomy/armadvsol.lua
  units/ArmBuildings/LandEconomy/armsolar.lua
  units/ArmBuildings/LandEconomy/armwin.lua
  units/ArmBuildings/LandUtil/armarad.lua
  units/ArmBuildings/LandUtil/armjamt.lua
  units/ArmBuildings/SeaEconomy/armtide.lua
  units/ArmShips/T2/armsjam.lua
  units/ArmVehicles/T2/armcroc.lua
  units/ArmVehicles/armfav.lua
  units/ArmVehicles/armflash.lua
  units/ArmVehicles/armpincer.lua
  units/CorAircraft/T2/coraca.lua
  units/CorAircraft/corbw.lua
  units/CorAircraft/corca.lua
  units/CorBots/T2/corack.lua
  units/CorBots/T2/corspy.lua
  units/CorBots/corak.lua
  units/CorBots/corck.lua
  units/CorBuildings/LandDefenceOffence/corexp.lua
  units/CorBuildings/LandDefenceOffence/corllt.lua
  units/CorBuildings/LandEconomy/corsolar.lua
  units/CorBuildings/LandEconomy/corwin.lua
  units/CorBuildings/LandUtil/corarad.lua
  units/CorHovercraft/corch.lua
  units/CorShips/T2/corsjam.lua
  units/CorVehicles/T2/coracv.lua
  units/CorVehicles/T2/corban.lua
  units/CorVehicles/T2/corparrow.lua
  units/CorVehicles/T2/cortrem.lua
  units/CorVehicles/corcv.lua
  units/CorVehicles/corfav.lua
  units/CorVehicles/corgarp.lua
  units/CorVehicles/corgator.lua
  units/CorVehicles/cormuskrat.lua
  weapons/spybombx.lua
Labels: Approved, Scheduled Balance Release

#4330 Armada-ify Banshee Take-2
  scripts/Units/armkam.bos
  scripts/Units/armkam.cob
  scripts/Units/armkam_clean.bos
  scripts/Units/armkam_clean.cob
  units/ArmAircraft/armkam.lua
Labels: Awaiting BLT Approval, Scheduled Balance Release

#4254 Update T1 core exploiter self d explosion to match core LLT
  units/CorBuildings/LandDefenceOffence/corexp.lua
Labels: Approved, Scheduled Balance Release
