Repository beyond-all-reason/Beyond-All-Reason, pull requests merged in 2025-05, with the labels that each got.

#4923 Cleaned up the names and "flavour text" from Extra Units descriptions
  gamedata/alldefs_post.lua
  language/en/units.json
Labels: UI

#4708 Ambassador/Negotiator closing animation interruption
  scripts/Units/armmerl.bos
  scripts/Units/armmerl.cob
  scripts/Units/armmerl_clean.bos
  scripts/Units/armmerl_clean.cob
  scripts/Units/corvroc.bos
  scripts/Units/corvroc.cob
  scripts/Units/corvroc_clean.bos
  scripts/Units/corvroc_clean.cob
Labels: Script / Animation

#5009 May 2025 balance patch
  changelog.txt
  units/ArmBots/T2/armspy.lua
  units/CorBots/T2/corspy.lua
  units/CorVehicles/T2/corban.lua
  units/CorVehicles/T2/corgol.lua
  weapons/spybombx.lua
Labels: Approved

#5023 Gridmenu layout fixes for Legion Hover lab
  luaui/configs/gridmenu_layouts.lua
Labels: UI, Keybinds

#4930 Settarget with shift keybind file fix
  luaui/configs/hotkeys/grid_keys.txt
  luaui/configs/hotkeys/grid_keys_60pct.txt
  luaui/configs/hotkeys/legacy_keys.txt
  luaui/configs/hotkeys/legacy_keys_60pct.txt
Labels: Keybinds

#4907 smart_selection: Decouple all modifier from append (fixed)
  luaui/Widgets/unit_smart_select.lua
  luaui/configs/hotkeys/chat_and_ui_keys.txt
Labels: Keybinds

#5061 Legion T1 AA and Rez Bot
  gamedata/armordefs.lua
  gamedata/icontypes.lua
  language/en/units.json
  luaui/configs/DeferredLightsGL4config.lua
  luaui/configs/buildmenu_sorting.lua
  luaui/configs/gridmenu_layouts.lua
  objects3d/Units/legaabot.s3o
  objects3d/Units/legaabot_dead.s3o
  objects3d/Units/legrezbot.s3o
  objects3d/Units/legrezbot_dead.s3o
  scripts/Units/legaabot.bos
  scripts/Units/legaabot.cob
  scripts/Units/legrezbot.bos
  scripts/Units/legrezbot.cob
  unitpics/legaabot.dds
  unitpics/legrezbot.dds
  units/Legion/Bots/legaabot.lua
  units/Legion/Bots/legrezbot.lua
  units/Legion/Constructors/legaceb.lua
  units/Legion/Labs/legamsub.lua
  units/Legion/Labs/leglab.lua
Labels: Legion

#5072 Legion Structures Update May 2025
  gamedata/armordefs.lua
  gamedata/icontypes.lua
  language/en/units.json
  luarules/configs/gui_soundeffects.lua
  luarules/configs/scav_spawn_defs.lua
  luarules/gadgets/fx_watersplash.lua
  luarules/gadgets/unit_juno_damage.lua
  luarules/gadgets/unit_juno_rework_damage.lua
  luaui/Widgets/gfx_lupsgl4_orbs.lua
  luaui/configs/DeferredLightsGL4config.lua
  luaui/configs/buildmenu_sorting.lua
  luaui/configs/gridmenu_layouts.lua
  objects3d/Units/legamphlab.s3o
  objects3d/Units/legamphlab_dead.s3o
  objects3d/Units/legfhp.s3o
  objects3d/Units/legfhp_dead.s3o
  objects3d/Units/legjuno.s3o
  objects3d/Units/legjuno_dead.s3o
  scripts/Units/legamphlab.bos
  scripts/Units/legamphlab.cob
  scripts/Units/legavp.bos
  scripts/Units/legfhp.bos
  scripts/Units/legfhp.cob
  scripts/Units/legjuno.bos
  scripts/Units/legjuno.cob
  unitpics/legamphlab.dds
  unitpics/legfhp.dds
  unitpics/leggeo.dds
  unitpics/legjuno.dds
  unitpics/legmstor.dds
  units/Legion/Constructors/legca.lua
  units/Legion/Constructors/legch.lua
  units/Legion/Constructors/legck.lua
  units/Legion/Constructors/legcs.lua
  units/Legion/Constructors/legcv.lua
  units/Legion/Constructors/legotter.lua
  units/Legion/Labs/legamphlab.lua
  units/Legion/Labs/legfhp.lua
  units/Legion/Legion EvoCom/legcomlvl10.lua
  units/Legion/Legion EvoCom/legcomlvl3.lua
  units/Legion/Legion EvoCom/legcomlvl4.lua
  units/Legion/Legion EvoCom/legcomlvl5.lua
  units/Legion/Legion EvoCom/legcomlvl6.lua
  units/Legion/Legion EvoCom/legcomlvl7.lua
  units/Legion/Legion EvoCom/legcomlvl8.lua
  units/Legion/Legion EvoCom/legcomlvl9.lua
  units/Legion/Utilities/legjuno.lua
Labels: Legion

#5114 Revert recent blueprint changes
  luaui/Widgets/api_blueprint.lua
  luaui/Widgets/cmd_blueprint.lua
Labels: Blueprint Widget

#5103 Fix drawing of unified range rings with flipped minimap.
  luaui/Shaders/weapon_range_rings_unified_gl4.vert.glsl
  luaui/Widgets/gui_attackrange_gl4.lua
Labels: Bug
