Repository beyond-all-reason/Beyond-All-Reason, pull requests merged in 2025-09, with the labels that each got.

#5788 Update Tiger Model
  luarules/configs/collisionvolumes.lua
  luaui/configs/DeferredLightsGL4config.lua
  objects3d/Units/correap.s3o
  objects3d/Units/correap_dead.s3o
  scripts/Units/correap.bos
  scripts/Units/correap.cob
  unitpics/correap.dds
  units/CorVehicles/T2/correap.lua
Labels: Modelling

#5791 Adjusts Thug model and animation
  objects3d/Units/corthud.s3o
  scripts/Units/corthud.bos
  scripts/Units/corthud.cob
  unitpics/corthud.dds
Labels: Modelling

#5778 Show transport weight indicators when you have multiple transports selected
  luaui/Widgets/gui_transport_weight_limit.lua
Labels: UI, Widget

#5837 Update proposed_unit_reworks_defs.lua
  unitbasedefs/proposed_unit_reworks_defs.lua
Labels: Awaiting BLT Approval
